# Generated by Django 3.2.2 on 2021-05-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210521_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
