# Generated by Django 3.2.2 on 2021-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(default='', max_length=100)),
                ('cus_email', models.CharField(default='', max_length=100)),
                ('cus_mobile', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
