# Generated by Django 3.2.2 on 2021-06-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_name', models.CharField(default='', max_length=100)),
                ('o_email', models.CharField(default='', max_length=100)),
                ('o_phone', models.CharField(default='', max_length=10)),
                ('o_add1', models.CharField(default='', max_length=1000)),
                ('o_add2', models.CharField(default='', max_length=1000)),
                ('o_city', models.CharField(default='', max_length=100)),
                ('o_state', models.CharField(default='', max_length=100)),
                ('o_zip', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
