# Generated by Django 3.2.2 on 2021-06-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_phone',
            new_name='o_mobile',
        ),
    ]
