# Generated by Django 3.2.2 on 2021-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_o_phone_order_o_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(default='', max_length=100)),
                ('u_email', models.CharField(default='', max_length=100)),
                ('u_psswrd', models.CharField(default='', max_length=10)),
                ('u_rpsswrd', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
