# Generated by Django 3.2.2 on 2021-06-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
