# Generated by Django 3.2.2 on 2021-06-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userl',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(default='', max_length=100)),
                ('u_email', models.CharField(default='', max_length=100)),
                ('u_psswrd', models.CharField(default='', max_length=100)),
                ('u_rpsswrd', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
