# Generated by Django 3.2.2 on 2021-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_o_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_amount',
            field=models.IntegerField(default=0),
        ),
    ]
